name = "buckwheat"
license = "MIT"
licenselink = "https://github.com/1ort/buckwheat/blob/master/LICENSE"
description = "A minimalist, responsive theme inspired by terminal ricing aesthetics."

homepage = "https://github.com/1ort/buckwheat"

tags = ["responsive", "minimal", "dark mode"]
features = []
min_version = "0.41.0"

[author]
  name = "Joe Roe"
  homepage = "https://joeroe.io"

